apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sathishbayer
spec:
  profile:
    displayName: Sathishkumar murugesan
    email: sathishkumar.murugesan.ext@bayer.com
  memberOf: []
